# Lancement : docker compose up -d

version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: off_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: off_dm
      MYSQL_USER: projet
      MYSQL_PASSWORD: projet
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: off_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_USER: projet
      PMA_PASSWORD: projet
      UPLOAD_LIMIT: 512M
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data: